<?php

namespace AppBundle\Repository;

/**
 * AsphaltingPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsphaltingPriceRepository extends \Doctrine\ORM\EntityRepository
{

    public function findPrices() {

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from('AppBundle:AsphaltingPrice', 'p')
            ->leftJoin('p.asphalt', 'a')->addSelect('a')
            ->leftJoin('a.type', 'ap')->addSelect('ap.id')
            ->groupBy('ap.id, a.id, p.id')
            ->getQuery()
            ->getResult()

            ;
    }
}
