<?php

namespace AppBundle\Repository;

/**
 * ProjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsphaltingRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * This function used to get single Asphalt
     *
     * @param $slug
     * @return mixed
     */
    public function findSingle($slug) {

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('a')
            ->from('AppBundle:Asphalting', 'a')
            ->leftJoin('a.type', 'at')->addSelect('at')
            ->leftJoin('a.price', 'ap')->addSelect('ap')
            ->where('a.slug =:sl')
            ->setParameter('sl', $slug)
            ->getQuery()->getOneOrNullResult()
            ;
    }


    /**
     * This function used to get single Asphalt
     *
     * @param $slug
     * @return mixed
     */
    public function findByTypes($slug) {

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('a.slug, a.updated')
            ->from('AppBundle:Asphalting', 'a')
            ->innerJoin('a.type', 'at', 'WITH', 'at.slug = :sl')->addSelect('at')
            ->setParameter('sl', $slug)
            ->getQuery()->getResult()
            ;
    }
}
