<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Document;
use AppBundle\Entity\Settings;
use AppBundle\Model\MainObjectabeleInterface;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;

/**
 * DocumentsListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentsListRepository extends \Doctrine\ORM\EntityRepository
{
}
