<?php

namespace AppBundle\Repository;

/**
 * EquipmentsPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentsPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
