<?php

namespace AppBundle\Repository;

/**
 * EquipmentTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentTypesRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * names and slugs
     */
    public function findAllForParent(){

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('et.slug, et.name, et.updated')
            ->from('AppBundle:EquipmentTypes', 'et')
            ->getQuery()->getResult()
            ;
    }

    /**
     * @return array
     * This function used to get data for list
     */
    public function findForList() {

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('et')
            ->from('AppBundle:EquipmentTypes', 'et')
            ->leftJoin('et.equipment', 'e')->addSelect('e')
            ->getQuery()->getResult()

            ;
    }



    /**
     * @return array
     * This function used to get data for list
     */
    public function findSugested($slug, $current) {

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('et')
            ->from('AppBundle:EquipmentTypes', 'et')
            ->leftJoin('et.equipment', 'e', 'WITH', 'e.slug != :cr')->addSelect('e')
            ->where('et.slug = :sl')
            ->setParameter('sl', $slug)
            ->setParameter('cr', $current)
            ->getQuery()->getResult()

            ;
    }


    /**
     * @return array
     * This function used to get all without current
     */
    public function findOther($slug) {

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('et')
            ->from('AppBundle:EquipmentTypes', 'et')
            ->leftJoin('et.equipment', 'e')->addSelect('e')
            ->where('et.slug != :sl')
            ->setParameter('sl', $slug)
            ->getQuery()->getResult()

            ;
    }

    /**
     * @return array
     * This function used to get data for list
     */
    public function findSingleType($slug) {

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('et')
            ->from('AppBundle:EquipmentTypes', 'et')
            ->leftJoin('et.equipment', 'e')->addSelect('e')
            ->where('et.slug = :sl')
            ->setParameter('sl', $slug)
            ->getQuery()->getResult()

            ;
    }


    /**
     * @return array
     * find pricing by types
     */
    public function findPricing() {

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('t, p')
            ->from('AppBundle:EquipmentTypes', 't')
//            ->innerJoin('t.equipment', 'e')
            ->innerJoin('t.price', 'p')
            ->getQuery()->getResult()
            ;
    }

}
