<?php

namespace AppBundle\Repository;

/**
 * EquipmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentsRepository extends \Doctrine\ORM\EntityRepository
{


    /**
     * This function used to get single Asphalt
     *
     * @param $slug
     * @return mixed
     */
    public function findSingle($slug) {

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('e')
            ->from('AppBundle:Equipments', 'e')
            ->leftJoin('e.type', 'et')->addSelect('et')
            ->leftJoin('e.price', 'ep')->addSelect('ep')
            ->where('e.slug = :sl')
            ->setParameter('sl', $slug)
            ->getQuery()->getOneOrNullResult()
            ;
    }

    public function findAllForParent() {

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('e.name, e.slug')
            ->from('AppBundle:Equipments', 'e')
            ->getQuery()->getResult()
            ;

    }


    public function findForList() {

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('e')
            ->from('AppBundle:Equipments', 'e')
            ->leftJoin('e.type', 'et')->addSelect('et')
            ->leftJoin('e.price', 'p')->addSelect('p')
            ->getQuery()->getResult()
            ;

    }
}
