<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Settings;
use AppBundle\Model\MainObjectabeleInterface;

/**
 * PagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesRepository extends \Doctrine\ORM\EntityRepository
{

    public function getViuewData($slug){

        $qPage = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from('AppBundle:Pages', 'p')
            ->innerJoin('AppBundle:Settings', 's', 'WITH', 's.fromId = p.id AND s.fromClassName = :clName')
            ->addSelect('s')
            ->where('p.slug = :sl')
            ->setParameter('sl', $slug)
            ->setParameter('clName', 'AppBundle\Entity\Pages')
            ->getQuery()->getResult()
            ;

        $page = null;
        $patents = [];
        foreach ($qPage as $item){

            if($item instanceof MainObjectabeleInterface){
                $page = $item;
            }

            if($item instanceof Settings){

                $patents['settings'][$item->getPosition()] = $item;

                $page->addToSettings($item);
                    $value = $this->getEntityManager()
                                    ->createQueryBuilder()
                                    ->select('p')
                                    ->from($item->getToClassName(), 'p')
                                    ->where('p.id = :ids')
                                    ->setParameter('ids', $item->getToId())
                                    ->getQuery()->getOneOrNullResult();


                $patents['parents'][$item->getPosition()] = $value;

            }

        }

        return $patents;
    }

    public function getKoko($slug){

        $qPage = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from('AppBundle:Pages', 'p')
            ->innerJoin('AppBundle:Settings', 's', 'WITH', 's.fromId = p.id AND s.fromClassName = :clName')
            ->addSelect('s')
            ->where('p.slug = :sl')
            ->setParameter('sl', $slug)
            ->setParameter('clName', 'AppBundle\Entity\Pages')
            ->getQuery()->getResult()
            ;

        return $qPage;
    }
}
